<?php

namespace Database\Seeders;

use Foostart\Category\Helpers\FoostartSeeder;
use Illuminate\Support\Facades\DB;
use App\Models\Vocabulary;
use Illuminate\Support\Facades\File;

class IrregularsSeeder extends FoostartSeeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        //Truncate table
        DB::table('irregulars')->truncate();

        //
        $data = [
            ["base" => 'abide', "past" => 'abode or abided', "participle" => 'abode or abided', "description" => 'To continue, To reside, To live'],
            ["base" => 'aby', "past" => 'abought', "participle" => 'abought', "description" => 'To make amends for something wrong'],
            ["base" => 'alight', "past" => 'alit or alighted', "participle" => 'alit or alighted', "description" => 'To get off a bus, train, etc.'],
            ["base" => 'arise', "past" => 'arose', "participle" => 'arisen', "description" => 'To originate, To get up from horizontal position, out of bed, To come into existence'],
            ["base" => 'awake', "past" => 'awoke', "participle" => 'awoken', "description" => 'To stop sleeping and become conscious'],
            ["base" => 'backbite', "past" => 'backbit', "participle" => 'backbitten', "description" => 'To speak badly about someone'],
            ["base" => 'backfit', "past" => 'backfit', "participle" => 'backfit', "description" => "To fit new parts into an older machine that weren't available when the machine was made"],
            ["base" => 'backlight', "past" => 'backlit', "participle" => 'backlit', "description" => 'To illuminate from behind (photography)'],
            ["base" => 'backslide', "past" => 'backslid', "participle" => 'backslid or backslidden', "description" => 'To stop making progress and start regressing'],
            ["base" => 'be', "past" => 'was or were', "participle" => 'been', "description" => 'To exist, live or occur., To have as a quality or a state, An auxiliary verb'],
            ["base" => 'bear', "past" => 'bore', "participle" => 'born or borne', "description" => 'To carry, To tolerate, To give birth to'],
            ["base" => 'beat', "past" => 'beat', "participle" => 'beaten', "description" => 'To hit repeatedly'],
            ["base" => 'become', "past" => 'became', "participle" => 'become', "description" => 'To come into existence'],
            ["base" => 'bedight', "past" => 'bedight or bedighted', "participle" => 'bedight or bedighted', "description" => 'To adorn, decorate'],
            ["base" => 'befall', "past" => 'befell', "participle" => 'befallen', "description" => 'To happen, To happen to somebody or something'],
            ["base" => 'beget', "past" => 'begot or begat', "participle" => 'begotten', "description" => 'To cause something to happen, To procreate'],
            ["base" => 'begin', "past" => 'began', "participle" => 'begun', "description" => 'To start something'],
            ["base" => 'begird', "past" => 'begirt or begirded', "participle" => 'begirt', "description" => 'To encircle'],
            ["base" => 'behight', "past" => 'behight', "participle" => 'behight', "description" => 'To promise or vow, To order'],
            ["base" => 'behold', "past" => 'beheld', "participle" => 'beheld', "description" => 'To become conscious of by seeing'],
            ["base" => 'belay', "past" => 'belayed', "participle" => 'belayed', "description" => 'To secure a boat with a rope, To tie up'],
            ["base" => 'bend', "past" => 'bent', "participle" => 'bent', "description" => 'To curve something by distorting its shape'],
            ["base" => 'bereave', "past" => 'bereft', "participle" => 'bereft or bereaved', "description" => 'To lose a relative through their death, To deprive'],
            ["base" => 'beseech', "past" => 'besought or beseeched', "participle" => 'besought or beseeched', "description" => 'To ask someone very insistently to do something'],
            ["base" => 'beset', "past" => 'beset', "participle" => 'beset', "description" => 'To be restricted and occupied by difficulties'],
            ["base" => 'bespeak', "past" => 'bespoke', "participle" => 'bespoken', "description" => 'To be a signal or symbol of something, To set aside or reserve something, To ask for'],
            ["base" => 'bestrew', "past" => 'bestrewed', "participle" => 'bestrewed or bestrewn', "description" => 'To cover a surface by throwing things about randomly'],
            ["base" => 'bestride', "past" => 'bestrode', "participle" => 'bestridden', "description" => 'To sit or stand with one leg on either side of something'],
            ["base" => 'bet', "past" => 'bet', "participle" => 'bet', "description" => 'To risk money against the result of a future event'],
            ["base" => 'betake', "past" => 'betook', "participle" => 'betaken', "description" => 'To go to a place'],
            ["base" => 'bethink', "past" => 'bethought', "participle" => 'bethought', "description" => 'To think about something, To remind yourself'],
            ["base" => 'beweep', "past" => 'bewept', "participle" => 'bewept', "description" => 'To cry for or over someone or something'],
            ["base" => 'bid', "past" => 'bade', "participle" => 'bidden', "description" => 'To command or urge someone to do something'],
            ["base" => 'bide', "past" => 'bided or bode', "participle" => 'bided', "description" => 'To wait for, To tolerate, To withstand'],
            ["base" => 'bind', "past" => 'bound', "participle" => 'bound', "description" => 'To tie something with string, or similar, to hold it'],
            ["base" => 'bite', "past" => 'bit', "participle" => 'bitten', "description" => 'To cut or hold with teeth'],
            ["base" => 'blaw', "past" => 'blawed', "participle" => 'blawn', "description" => 'To blow'],
            ["base" => 'bleed', "past" => 'bled', "participle" => 'bled', "description" => 'To lose blood through a cut in the skin'],
            ["base" => 'blend', "past" => 'blended or blent', "participle" => 'blended or blent', "description" => 'To mix together'],
            ["base" => 'bless', "past" => 'blessed or blest', "participle" => 'blessed or blest', "description" => 'To wish or confer happiness, To make holy'],
            ["base" => 'blow', "past" => 'blew', "participle" => 'blown', "description" => 'To move air, wind and gases'],
            ["base" => 'bottle-feed', "past" => 'bottle-fed', "participle" => 'bottle-fed', "description" => 'To feed a baby with a bottle'],
            ["base" => 'bowstring', "past" => 'bowstrung or bowstringed', "participle" => 'bowstrung', "description" => 'To strangle with the string from a bow'],
            ["base" => 'break', "past" => 'broke', "participle" => 'broken', "description" => 'To cause something to separate into at least two pieces'],
            ["base" => 'breast-feed', "past" => 'breast-fed', "participle" => 'breast-fed', "description" => 'To feed a baby with breast milk'],
            ["base" => 'breed', "past" => 'bred', "participle" => 'bred', "description" => 'To produce animals or plants by controlling their reproduction'],
            ["base" => 'bring', "past" => 'brought', "participle" => 'brought', "description" => 'To carry or convey something to the place where you are going'],
            ["base" => 'broadcast', "past" => 'broadcast or broadcasted', "participle" => 'broadcast or broadcasted', "description" => 'To transmit radio or TV signals'],
            ["base" => 'browbeat', "past" => 'browbeat', "participle" => 'browbeat or browbeaten', "description" => 'To put pressure on someone or bully them to do something'],
            ["base" => 'build', "past" => 'built', "participle" => 'built', "description" => 'To construct'],
            ["base" => 'burn', "past" => 'burnt or burned', "participle" => 'burnt or burned', "description" => 'To consume or be consumed by fire'],
            ["base" => 'burst', "past" => 'burst', "participle" => 'burst', "description" => 'To break something open, usually by internal pressure, such as a balloon with too much air in it'],
            ["base" => 'bust', "past" => 'bust', "participle" => 'bust', "description" => 'To break'],
            ["base" => 'buy', "past" => 'bought', "participle" => 'bought', "description" => 'To acquire something in exchange for money'],
            ["base" => 'cast', "past" => 'cast', "participle" => 'cast', "description" => 'To throw or project something'],
            ["base" => 'catch', "past" => 'caught', "participle" => 'caught', "description" => 'To receive, To stop and hold a moving object, usua…th your hands, To make something unable to escape'],
            ["base" => 'cheerlead', "past" => 'cheerled', "participle" => 'cheerled', "description" => 'To cheer and support a team in an organised group'],
            ["base" => 'chide', "past" => 'chid', "participle" => 'chid or chidden', "description" => 'To tell somebody off when they have done something wrong'],
            ["base" => 'choose', "past" => 'chose', "participle" => 'chosen', "description" => 'To select'],
            ["base" => 'clap', "past" => 'clapped or clapt', "participle" => 'clapped or clapt', "description" => 'To hit your hands together to make a sound to show approval, To make a loud noise, like thunder'],
            ["base" => 'clear-cut', "past" => 'clear-cut', "participle" => 'clear-cut', "description" => 'To cut down all trees in an area'],
            ["base" => 'cleave', "past" => 'cleft or cleaved or clove', "participle" => 'cleft or cleaved or cloven', "description" => 'To separate or divide something, often with force, To stick or hold together'],
            ["base" => 'cleek', "past" => 'claught or claucht or cleeked', "participle" => 'cleeked', "description" => 'To grasp or take hold of'],
            ["base" => 'clepe', "past" => 'cleped', "participle" => 'cleped or ycleped or yclept', "description" => 'To call or name'],
            ["base" => 'cling', "past" => 'clung', "participle" => 'clung', "description" => 'To hold on to or to stick to'],
            ["base" => 'clothe', "past" => 'clad or clothed', "participle" => 'clad or clothed', "description" => 'To dress someone or provide them with clothes'],
            ["base" => 'colorbreed', "past" => 'colorbred', "participle" => 'colorbred', "description" => 'To breed an animal to be of a particular color'],
            ["base" => 'colorcast', "past" => 'colorcast', "participle" => 'colorcast', "description" => 'To broadcast in color'],
            ["base" => 'come', "past" => 'came', "participle" => 'come', "description" => 'To move towards or to arrive at a specified place, time or situation'],
            ["base" => 'cost', "past" => 'cost', "participle" => 'cost', "description" => 'The amount of money required to buy something; it costs five dollars.'],
            ["base" => 'cost-cut', "past" => 'cost-cut', "participle" => 'cost-cut', "description" => 'To reduce costs or expenditure'],
            ["base" => 'counterdraw', "past" => 'counterdrew', "participle" => 'counterdrawn', "description" => 'To copy by tracing'],
            ["base" => 'counterlight', "past" => 'counterlit', "participle" => 'counterlit', "description" => 'To light something directly from opposite sides'],
            ["base" => 'crash-dive', "past" => 'crash-dived', "participle" => 'crash-dived', "description" => 'To go down very quickly'],
            ["base" => 'creep', "past" => 'crept', "participle" => 'crept', "description" => 'To move along the ground lying down'],
            ["base" => 'creep-feed', "past" => 'creep-fed', "participle" => 'creep-fed', "description" => "To feed young animals in a special area that adult animals can't get in"],
            ["base" => 'crib-bite', "past" => 'crib-bit', "participle" => 'crib-bitten', "description" => 'To bite its manger and swallow air (of a horse)'],
            ["base" => 'cross-bite', "past" => 'cross-bit', "participle" => 'cross-bitten', "description" => 'To thwart or stop something happening by deception'],
            ["base" => 'cross-string', "past" => 'cross-strung', "participle" => 'cross-strung', "description" => 'To place bass strings on a piano across the treble strings'],
            ["base" => 'crossbreed', "past" => 'crossbred', "participle" => 'crossbred', "description" => 'To breed animals or plants of different species, l…le, which is a crossbreed of a donkey and a horse'],
            ["base" => 'crosscut', "past" => 'crosscut', "participle" => 'crosscut', "description" => 'To move between scenes or stories in a film or narrative'],
            ["base" => 'crosslight', "past" => 'crosslit', "participle" => 'crosslit', "description" => 'To illuminate from different sides, but not directly opposite'],
            ["base" => 'crow', "past" => 'crowed or crew', "participle" => 'crowed', "description" => 'To boast To utter a sound indicating pleasure'],
            ["base" => 'cut', "past" => 'cut', "participle" => 'cut', "description" => 'To break the surface of something with a knife or similar tool'],
            ["base" => 'dare', "past" => 'dared or durst', "participle" => 'dared', "description" => 'To have sufficient courage'],
            ["base" => 'daydream', "past" => 'daydreamt or daydreamt', "participle" => 'daydreamt or daydreamt', "description" => 'To have dream-like thoughts when a wake, To have a fantasy'],
            ["base" => 'deal', "past" => 'dealt', "participle" => 'dealt', "description" => 'To distribute, especially playing cards in games'],
            ["base" => 'deep-freeze', "past" => 'deep-froze', "participle" => 'deep-frozen', "description" => 'To freeze or store frozen, To suspend progress or activity'],
            ["base" => 'dig', "past" => 'dug', "participle" => 'dug', "description" => 'To make a hole in the ground'],
            ["base" => 'dight', "past" => 'dight or dighted', "participle" => 'dight or dighted', "description" => 'To dictate orders'],
            ["base" => 'dispread', "past" => 'dispread', "participle" => 'dispread', "description" => 'To spread out'],
            ["base" => 'disprove', "past" => 'disproved', "participle" => 'disproven or disproved', "description" => 'To prove that something is fake or wrong'],
            ["base" => 'dive', "past" => 'dived or dove', "participle" => 'dived', "description" => 'To jump head first into water, To fall quickly'],
            ["base" => 'do', "past" => 'did', "participle" => 'done', "description" => 'To perform or carry out'],
            ["base" => 'dogfight', "past" => 'dogfought', "participle" => 'dogfought', "description" => 'To fight in aeroplanes, To arrange a fight between dogs for sport'],
            ["base" => 'dow', "past" => 'dought or dowed', "participle" => 'dought or dowed', "description" => 'To have the ability to do something, To do well'],
            ["base" => 'draw', "past" => 'drew', "participle" => 'drawn', "description" => 'To make a picture using a pen or pencil'],
            ["base" => 'dream', "past" => 'dreamt or dreamed', "participle" => 'dreamt or dreamed', "description" => 'To see visual images while sleeping'],
            ["base" => 'drink', "past" => 'drank', "participle" => 'drunk', "description" => 'To consume liquids'],
            ["base" => 'drip-feed', "past" => 'drip-fed', "participle" => 'drip-fed', "description" => 'To feed someone with fluids going into the vein, To release information very slowly, bit by bit'],
            ["base" => 'drive', "past" => 'drove', "participle" => 'driven', "description" => 'To operate and control a car or other vehicle'],
            ["base" => 'dwell', "past" => 'dwelt', "participle" => 'dwelt', "description" => 'To reside or live somewhere'],
            ["base" => 'eat', "past" => 'ate', "participle" => 'eaten', "description" => 'To consume solid food'],
            ["base" => 'end-run', "past" => 'end-ran', "participle" => 'end-run', "description" => 'To avoid doing something by cheating or deceit'],
            ["base" => 'engird', "past" => 'engirt', "participle" => 'engirt', "description" => 'To encircle, encompass'],
            ["base" => 'engrave', "past" => 'engraved', "participle" => 'engraved or engraven', "description" => 'To carve letters or a pattern into the surface of something'],
            ["base" => 'enwind', "past" => 'enwound', "participle" => 'enwound', "description" => 'To make into a coil, To wrap around something'],
            ["base" => 'fall', "past" => 'fell', "participle" => 'fallen', "description" => 'To move downwards or to the ground'],
            ["base" => 'fast-cut', "past" => 'fast-cut', "participle" => 'fast-cut', "description" => 'To cut quickly from one scene to another in a film'],
            ["base" => 'feed', "past" => 'fed', "participle" => 'fed', "description" => 'To give or supply food'],
            ["base" => 'feel', "past" => 'felt', "participle" => 'felt', "description" => 'To sense by touch, To experience an emotion, or sensation'],
            ["base" => 'fight', "past" => 'fought', "participle" => 'fought', "description" => 'To try to hurt or kill someone in combat or war'],
            ["base" => 'find', "past" => 'found', "participle" => 'found', "description" => 'To discover something either by chance or when looking for it'],
            ["base" => 'fit', "past" => 'fit or fitted', "participle" => 'fit or fitted', "description" => 'To be the correct size, for clothes, etc. (fit/fit…ure someone for size (fit fit/fitted/ fit/fitted)'],
            ["base" => 'flash-freeze', "past" => 'flash-froze', "participle" => 'flash-frozen', "description" => 'To freeze food very rapidly to preserve taste and nutrients'],
            ["base" => 'flee', "past" => 'fled', "participle" => 'fled', "description" => 'To run away in order to find safety'],
            ["base" => 'fling', "past" => 'flung', "participle" => 'flung', "description" => 'To throw or move something suddenly'],
            ["base" => 'floodlight', "past" => 'floodlit', "participle" => 'floodlit', "description" => 'To use powerful lights to illuminate something outside at night'],
            ["base" => 'fly', "past" => 'flew', "participle" => 'flown', "description" => 'To move through the air, To travel by aeroplane'],
            ["base" => 'flyblow', "past" => 'flyblew', "participle" => 'flyblown', "description" => 'To contaminate by laying eggs, the way a fly does'],
            ["base" => 'forbear', "past" => 'forbore', "participle" => 'forborne', "description" => 'Not to use or talk about something'],
            ["base" => 'forbid', "past" => 'forbade or forbad', "participle" => 'forbidden', "description" => 'To prohibit'],
            ["base" => 'force-feed', "past" => 'force-fed', "participle" => 'force-fed', "description" => "To feed someone who refuses or doesn't want to eat"],
            ["base" => 'fordo', "past" => 'fordid', "participle" => 'fordone', "description" => 'To ruin or destroy'],
            ["base" => 'forecast', "past" => 'forecast or forecasted', "participle" => 'forecast or forecasted', "description" => 'To predict the future'],
            ["base" => 'forefeel', "past" => 'forefelt', "participle" => 'forefelt', "description" => 'To have a feeling before something happens, To have a premonition'],
            ["base" => 'forego', "past" => 'forewent', "participle" => 'foregone', "description" => 'To proceed something, To go without something'],
            ["base" => 'foreknow', "past" => 'foreknew', "participle" => 'foreknown', "description" => 'To know something beforehand'],
            ["base" => 'forerun', "past" => 'foreran', "participle" => 'forerun', "description" => 'To go before something, To show that something is going to happen'],
            ["base" => 'foresee', "past" => 'foresaw', "participle" => 'foreseen', "description" => 'To predict or see the future'],
            ["base" => 'foreshow', "past" => 'foreshowed', "participle" => 'foreshown', "description" => 'To show something or make it known beforehand, To foretell'],
            ["base" => 'forespeak', "past" => 'forespoke', "participle" => 'forespoken', "description" => 'To predict, To speak of something beforehand'],
            ["base" => 'foretell', "past" => 'foretold', "participle" => 'foretold', "description" => 'To predict the future'],
            ["base" => 'forget', "past" => 'forgot', "participle" => 'forgotten', "description" => 'To be unable to remember something'],
            ["base" => 'forgive', "past" => 'forgave', "participle" => 'forgiven', "description" => 'To pardon or stop being angry with someone who has offended you'],
            ["base" => 'forlese', "past" => 'forlore', "participle" => 'forlorn', "description" => 'To lose completely'],
            ["base" => 'forsake', "past" => 'forsook', "participle" => 'forsaken', "description" => 'To give something up, To abandon'],
            ["base" => 'forswear', "past" => 'forswore', "participle" => 'forsworn', "description" => 'To make a false promise or oath'],
            ["base" => 'fraught', "past" => 'fraught or fraughted', "participle" => 'fraught or fraughted', "description" => 'To stock To load a ship, etc, To hire a ship, etc'],
            ["base" => 'free-fall', "past" => 'free-fell', "participle" => 'free-fallen', "description" => 'To drop or fall suddenly, To fall through the air without opening a parachute'],
            ["base" => 'freeze', "past" => 'froze', "participle" => 'frozen', "description" => 'To make liquids into solids by cold temperatures, To store food below zero degrees centigrade'],
            ["base" => 'frostbite', "past" => 'frostbit', "participle" => 'frostbitten', "description" => 'To injure or damage part of the body through extreme cold'],
            ["base" => 'gainsay', "past" => 'gainsaid', "participle" => 'gainsaid', "description" => 'To contradict or deny'],
            ["base" => 'geld', "past" => 'gelded or gelt', "participle" => 'gelded or gelt', "description" => 'To castrate an animal'],
            ["base" => 'get', "past" => 'got', "participle" => 'got or gotten', "description" => 'To obtain, catch or receive'],
            ["base" => 'ghostwrite', "past" => 'ghostwrote', "participle" => 'ghostwritten', "description" => 'To write for someone else, who will put their name as the author'],
            ["base" => 'gild', "past" => 'gilt or gilded', "participle" => 'gilt or gilded', "description" => 'To cover something with a thin layer of gold'],
            ["base" => 'gin', "past" => 'gan', "participle" => 'gan', "description" => 'To begin something'],
            ["base" => 'gird', "past" => 'girded or girt', "participle" => 'girded or girt', "description" => 'To secure or encircle something with a belt or bend'],
            ["base" => 'give', "past" => 'gave', "participle" => 'given', "description" => 'To offer something as a present'],
            ["base" => 'gnaw', "past" => 'gnawed', "participle" => 'gnawed or gnawn', "description" => 'To bite or chew, To cause worry'],
            ["base" => 'go', "past" => 'went', "participle" => 'gone or been', "description" => 'To travel to a place'],
            ["base" => 'grave', "past" => 'graved', "participle" => 'graven or graved', "description" => 'To dig, To carve, To fix in the memory'],
            ["base" => 'grind', "past" => 'ground', "participle" => 'ground', "description" => 'To break something into a powder'],
            ["base" => 'grow', "past" => 'grew', "participle" => 'grown', "description" => 'To increase in size'],
            ["base" => 'hagride', "past" => 'hagrode', "participle" => 'hagridden', "description" => 'To torment or cause nightmares'],
            ["base" => 'halterbreak', "past" => 'halterbroke', "participle" => 'halterbroken', "description" => 'To break a horse in, to get it used to wearing a halter'],
            ["base" => 'hamstring', "past" => 'hamstrung or hamstringed', "participle" => 'hamstrung or hamstringed', "description" => 'To make things difficult for someone doing something'],
            ["base" => 'hand-feed', "past" => 'hand-fed', "participle" => 'hand-fed', "description" => 'To give food by hand'],
            ["base" => 'hand-ride', "past" => 'hand-rode', "participle" => 'hand-ridden', "description" => 'To control an animal by hand'],
            ["base" => 'handsew', "past" => 'handsewed', "participle" => 'handsewn or handsewed', "description" => 'To sew by hand'],
            ["base" => 'handwrite', "past" => 'handwrote', "participle" => 'handwritten', "description" => 'To write with a pen or pencil rather than a word processor'],
            ["base" => 'hang', "past" => 'hung or hanged', "participle" => 'hung or hanged', "description" => 'To suspend from a support'],
            ["base" => 'have', "past" => 'had', "participle" => 'had', "description" => 'To possess, To do, An auxiliary verb'],
            ["base" => 'hear', "past" => 'heard', "participle" => 'heard', "description" => 'To detect or perceive sound'],
            ["base" => 'heave', "past" => 'heaved or hove', "participle" => 'heaved or hove', "description" => 'To lift something heavy, To throw something heavy'],
            ["base" => 'hew', "past" => 'hewed', "participle" => 'hewn', "description" => 'To cut things into pieces'],
            ["base" => 'hide', "past" => 'hid', "participle" => 'hidden', "description" => 'To conceal or put something where it cannot be seen'],
            ["base" => 'hight', "past" => 'hote or hight', "participle" => 'hoten', "description" => 'To name, To promise, To command'],
            ["base" => 'hit', "past" => 'hit', "participle" => 'hit', "description" => 'To touch somebody or something with force'],
            ["base" => 'hoise', "past" => 'hoised or hoist', "participle" => 'hoised or hoist', "description" => 'To hoist or lift'],
            ["base" => 'hoist', "past" => 'hoist or hoisted', "participle" => 'hoist or hoisted', "description" => 'To raise or lift using ropes, etc'],
            ["base" => 'hold', "past" => 'held', "participle" => 'held', "description" => 'To secure something in your hand, To contain'],
            ["base" => 'house-sit', "past" => 'house-sat', "participle" => 'house-sat', "description" => "To stay in someone's house to look after it while they are away"],
            ["base" => 'housebreak', "past" => 'housebroke', "participle" => 'housebroken', "description" => 'To train an animal to live in a house'],
            ["base" => 'hurt', "past" => 'hurt', "participle" => 'hurt', "description" => 'To cause pain, injury or stress, To experience pain, injury or stress'],
            ["base" => 'inbreed', "past" => 'inbred', "participle" => 'inbred', "description" => 'To produce babies with health problems by sexual relations between close relatives'],
            ["base" => 'indwell', "past" => 'indwelt', "participle" => 'indwelt', "description" => 'To inhabit, To exist as a guiding principle'],
            ["base" => 'inhold', "past" => 'inheld', "participle" => 'inheld', "description" => 'To have as an inherent characteristic'],
            ["base" => 'inlay', "past" => 'inlaid', "participle" => 'inlaid', "description" => 'To put a different material inside another for decoration, with a flat surface'],
            ["base" => 'input', "past" => 'input or inputted', "participle" => 'input or inputted', "description" => 'To enter data into a computer'],
            ["base" => 'inset', "past" => 'inset', "participle" => 'inset', "description" => 'To put a picture or graphic inside a larger one'],
            ["base" => 'interblend', "past" => 'interblended or interblent', "participle" => 'interblended or interblent', "description" => 'To blend things together'],
            ["base" => 'interbreed', "past" => 'interbred', "participle" => 'interbred', "description" => 'To mix species or groups sexually'],
            ["base" => 'intercut', "past" => 'intercut', "participle" => 'intercut', "description" => 'To move between different scenes or stories in a film or narrative'],
            ["base" => 'intergrave', "past" => 'intergraved', "participle" => 'intergraved', "description" => 'To carve or engrave in alternate sections'],
            ["base" => 'interlay', "past" => 'interlaid', "participle" => 'interlaid', "description" => 'To place among or between things'],
            ["base" => 'interset', "past" => 'interset', "participle" => 'interset', "description" => 'To set among or between things'],
            ["base" => 'interweave', "past" => 'interwove', "participle" => 'interwoven', "description" => 'To join or mix together'],
            ["base" => 'interwind', "past" => 'interwound', "participle" => 'interwound', "description" => 'To wind together or intertwine'],
            ["base" => 'inweave', "past" => 'inwove or inweaved', "participle" => 'inwoven or inweaved', "description" => 'To weave things together'],
            ["base" => 'inwind', "past" => 'inwound', "participle" => 'inwound', "description" => 'To wrap or coil around'],
            ["base" => 'jerry-build', "past" => 'jerry-built', "participle" => 'jerry-built', "description" => 'To build something cheaply and badly'],
            ["base" => 'keep', "past" => 'kept', "participle" => 'kept', "description" => 'To have possession, To make somebody or something stay in a particular place'],
            ["base" => 'ken', "past" => 'kent or kenned', "participle" => 'kent or kenned', "description" => 'To know'],
            ["base" => 'kneel', "past" => 'knelt or kneeled', "participle" => 'knelt or kneeled', "description" => 'To support yourself on your knees'],
            ["base" => 'knit', "past" => 'knit or knitted', "participle" => 'knit or knitted', "description" => 'To make clothes such as pullovers out of wool'],
            ["base" => 'know', "past" => 'knew', "participle" => 'known', "description" => 'To be acquainted with, To have correctly in your memory'],
            ["base" => 'lade', "past" => 'laded', "participle" => 'laden or laded', "description" => 'To load (put goods onto) a ship'],
            ["base" => 'landslide', "past" => 'landslid or landslided', "participle" => 'landslid or landslided', "description" => 'To win a convincing and easy victory in an election'],
            ["base" => 'lay', "past" => 'laid', "participle" => 'laid', "description" => 'To put something in a horizontal position'],
            ["base" => 'lead', "past" => 'led', "participle" => 'led', "description" => 'To take someone somewhere or guide them, To be in command'],
            ["base" => 'lean', "past" => 'leant or leaned', "participle" => 'leant or leaned', "description" => 'To place something at an incline for support against something'],
            ["base" => 'leap', "past" => 'leapt or leaped', "participle" => 'leapt or leaped', "description" => 'To jump'],
            ["base" => 'learn', "past" => 'learnt or learned', "participle" => 'learnt or learned', "description" => 'To acquire knowledge'],
            ["base" => 'leave', "past" => 'left', "participle" => 'left', "description" => 'To go out of a place'],
            ["base" => 'lend', "past" => 'lent', "participle" => 'lent', "description" => 'To give somebody money that must be returned'],
            ["base" => 'lep', "past" => 'lept', "participle" => 'lept', "description" => 'To leap'],
            ["base" => 'let', "past" => 'let', "participle" => 'let', "description" => 'To allow something to happen, To allow someone to do something'],
            ["base" => 'lie', "past" => 'lay', "participle" => 'lain', "description" => 'To get into or be in a horizontal position'],
            ["base" => 'light', "past" => 'lit', "participle" => 'lit', "description" => 'To make something burn'],
            ["base" => 'linebreed', "past" => 'linebred', "participle" => 'linebred', "description" => 'Breed animals from a particular family'],
            ["base" => 'lip-read', "past" => 'lip-read', "participle" => 'lip-read', "description" => 'To work out what someone is saying from the movements of their mouth'],
            ["base" => 'lose', "past" => 'lost', "participle" => 'lost', "description" => 'Not to have something because you do not know where it is'],
            ["base" => 'make', "past" => 'made', "participle" => 'made', "description" => 'To create or construct something, To cause somebody to do something, To perform an action'],
            ["base" => 'mean', "past" => 'meant', "participle" => 'meant', "description" => 'To signify, To intend'],
            ["base" => 'meet', "past" => 'met', "participle" => 'met', "description" => "To make somebody's acquaintance"],
            ["base" => 'melt', "past" => 'melted', "participle" => 'molten or melted', "description" => 'To change from solid into a liquid as the temperature goes up'],
            ["base" => 'misbecome', "past" => 'misbecame', "participle" => 'misbecome', "description" => 'Not to suit'],
            ["base" => 'miscast', "past" => 'miscast', "participle" => 'miscast', "description" => 'To choose the wrong actor for a role'],
            ["base" => 'mischoose', "past" => 'mischose', "participle" => 'mischosen', "description" => 'To choose wrongly'],
            ["base" => 'miscut', "past" => 'miscut', "participle" => 'miscut', "description" => 'To cut something wrongly or badly'],
            ["base" => 'misdeal', "past" => 'misdealt', "participle" => 'misdealt', "description" => 'To distribute playing cards wrongly in a game'],
            ["base" => 'misdo', "past" => 'misdid', "participle" => 'misdone', "description" => 'To harm or injure'],
            ["base" => 'misfall', "past" => 'misfell', "participle" => 'misfallen', "description" => 'To happen unluckily'],
            ["base" => 'misfeed', "past" => 'misfed', "participle" => 'misfed', "description" => 'To feed incorrectly, To jam printers, photocopiers, etc, by feeding the paper incorrectly'],
            ["base" => 'misgive', "past" => 'misgave', "participle" => 'misgiven', "description" => 'To become suspicious or worried'],
            ["base" => 'mishear', "past" => 'misheard', "participle" => 'misheard', "description" => 'To hear something incorrectly'],
            ["base" => 'mishit', "past" => 'mishit', "participle" => 'mishit', "description" => 'To hit a ball badly or inaccurately'],
            ["base" => 'misknow', "past" => 'misknew', "participle" => 'misknown', "description" => 'To have the wrong idea about something'],
            ["base" => 'mislay', "past" => 'mislaid', "participle" => 'mislaid', "description" => 'To lose or put something where you cannot find it'],
            ["base" => 'mislead', "past" => 'misled', "participle" => 'misled', "description" => 'To make someone behave wrongly, To deceive'],
            ["base" => 'mislearn', "past" => 'mislearnt or mislearned', "participle" => 'mislearnt or mislearned', "description" => 'To learn wrongly'],
            ["base" => 'misread', "past" => 'misread', "participle" => 'misread', "description" => 'To read something incorrectly'],
            ["base" => 'missay', "past" => 'missaid', "participle" => 'missaid', "description" => 'To say something incorrectly, To talk badly about someone'],
            ["base" => 'missend', "past" => 'missent', "participle" => 'missent', "description" => 'To send to the wrong place or person'],
            ["base" => 'misset', "past" => 'misset', "participle" => 'misset', "description" => 'To set or place wrongly or incorrectly'],
            ["base" => 'misspeak', "past" => 'misspoke', "participle" => 'misspoken', "description" => 'To say or pronounce something wrongly, To say something that is incorrect or inaccurate'],
            ["base" => 'misspell', "past" => 'misspelt or misspelled', "participle" => 'misspelt or misspelled', "description" => 'To write a word without using the correct letters'],
            ["base" => 'misspend', "past" => 'misspent', "participle" => 'misspent', "description" => 'To waste time or money'],
            ["base" => 'misswear', "past" => 'misswore', "participle" => 'missworn', "description" => 'To swear or make an oath falsely'],
            ["base" => 'mistake', "past" => 'mistook', "participle" => 'mistaken', "description" => 'Not to understand, To confuse somebody with someone else'],
            ["base" => 'misteach', "past" => 'mistaught', "participle" => 'mistaught', "description" => 'To teach wrongly or incorrectly'],
            ["base" => 'mistell', "past" => 'mistold', "participle" => 'mistold', "description" => 'To tell something wrongly'],
            ["base" => 'misthink', "past" => 'misthought', "participle" => 'misthought', "description" => 'To have mistaken thoughts or ideas'],
            ["base" => 'misunderstand', "past" => 'misunderstood', "participle" => 'misunderstood', "description" => 'Not to understand'],
            ["base" => 'miswear', "past" => 'misswore', "participle" => 'misworn', "description" => 'To wear badly'],
            ["base" => 'miswed', "past" => 'miswed or miswedded', "participle" => 'miswed or miswedded', "description" => 'To marry wrongly'],
            ["base" => 'miswrite', "past" => 'miswrote', "participle" => 'miswritten', "description" => 'To write something incorrectly'],
            ["base" => 'mow', "past" => 'mowed', "participle" => 'mown', "description" => 'To cut grass or cereals'],
            ["base" => 'naysay', "past" => 'naysaid', "participle" => 'naysaid', "description" => 'To oppose or criticise'],
            ["base" => 'nose-dive', "past" => 'nose-dived or nose-dove', "participle" => 'nose-dived or nose-dove', "description" => 'To dive or plunge nose first (aircraft)'],
            ["base" => 'offset', "past" => 'offset', "participle" => 'offset', "description" => 'To compensate or counterbalance'],
            ["base" => 'outbid', "past" => 'outbid', "participle" => 'outbid', "description" => 'To offer more money than someone in an auction or sale'],
            ["base" => 'outbreed', "past" => 'outbred', "participle" => 'outbred', "description" => 'To breed faster than others'],
            ["base" => 'outdo', "past" => 'outdid', "participle" => 'outdone', "description" => 'To do better than someone'],
            ["base" => 'outdraw', "past" => 'outdrew', "participle" => 'outdrawn', "description" => 'To pull out, To pull a gun faster than an opponent'],
            ["base" => 'outdrink', "past" => 'outdrank', "participle" => 'outdrunk', "description" => 'To drink more than someone else, usually alcohol'],
            ["base" => 'outdrive', "past" => 'outdrove', "participle" => 'outdriven', "description" => 'To drive faster or better'],
            ["base" => 'outfight', "past" => 'outfought', "participle" => 'outfought', "description" => 'To fight better than someone'],
            ["base" => 'outfly', "past" => 'outflew', "participle" => 'outflown', "description" => 'To fly faster or further'],
            ["base" => 'outgrow', "past" => 'outgrew', "participle" => 'outgrown', "description" => 'To grow faster than something or someone, To become too big or mature for something'],
            ["base" => 'outlay', "past" => 'outlaid', "participle" => 'outlaid', "description" => 'To spend money for a particular purpose'],
            ["base" => 'outleap', "past" => 'outleapt or outleaped', "participle" => 'outleapt or outleaped', "description" => 'To jump or leap further or higher'],
            ["base" => 'output', "past" => 'output or outputted', "participle" => 'output or outputted', "description" => 'To put out or produce'],
            ["base" => 'outride', "past" => 'outrode', "participle" => 'outridden', "description" => 'To ride faster than someone'],
            ["base" => 'outrun', "past" => 'outran', "participle" => 'outrun', "description" => 'To run or go faster than someone'],
            ["base" => 'outsee', "past" => 'outsaw', "participle" => 'outseen', "description" => 'To see further, To have greater foresight'],
            ["base" => 'outsell', "past" => 'outsold', "participle" => 'outsold', "description" => 'To sell more than something or someone'],
            ["base" => 'outshine', "past" => 'outshone', "participle" => 'outshone', "description" => 'To be better than someone'],
            ["base" => 'outshoot', "past" => 'outshot', "participle" => 'outshot', "description" => 'To shoot faster or better'],
            ["base" => 'outsing', "past" => 'outsang', "participle" => 'outsung', "description" => 'To sing better or louder than someone'],
            ["base" => 'outsit', "past" => 'outsat', "participle" => 'outsat', "description" => 'To sit for longer than someone'],
            ["base" => 'outsleep', "past" => 'outslept', "participle" => 'outslept', "description" => 'To sleep for longer than someone'],
            ["base" => 'outsmell', "past" => 'outsmelled', "participle" => 'outsmelled', "description" => 'To have a better sense of smell'],
            ["base" => 'outspeak', "past" => 'outspoke', "participle" => 'outspoken', "description" => 'To speak better or more than someone'],
            ["base" => 'outspeed', "past" => 'outsped', "participle" => 'outsped', "description" => 'To go faster than someone or something'],
            ["base" => 'outspend', "past" => 'outspent', "participle" => 'outspent', "description" => 'To spend more than someone'],
            ["base" => 'outspin', "past" => 'outspun', "participle" => 'outspun', "description" => 'To finish or die'],
            ["base" => 'outspring', "past" => 'outsprang', "participle" => 'outsprung', "description" => 'To spring or jump out'],
            ["base" => 'outstand', "past" => 'outstood', "participle" => 'outstood', "description" => 'To be clearly different or better'],
            ["base" => 'outswear', "past" => 'outswore', "participle" => 'outsworn', "description" => 'To exceed someone in swearing - oaths or bad language'],
            ["base" => 'outswim', "past" => 'outswam', "participle" => 'outswum', "description" => 'To swim faster or further than someone'],
            ["base" => 'outtell', "past" => 'outtold', "participle" => 'outtold', "description" => 'To be better or exceed in telling or calculating'],
            ["base" => 'outthink', "past" => 'outthought', "participle" => 'outthought', "description" => 'To think better ideas than someone'],
            ["base" => 'outthrow', "past" => 'outthrew', "participle" => 'outthrown', "description" => 'To throw further or more accurately'],
            ["base" => 'outwear', "past" => 'outwore', "participle" => 'outworn', "description" => 'To last longer (of materials, clothes, etc)'],
            ["base" => 'outwind', "past" => 'outwound', "participle" => 'outwound', "description" => 'To unloose'],
            ["base" => 'outwork', "past" => 'outworked or outwrought', "participle" => 'outworked or outwrought', "description" => 'To work harder or better'],
            ["base" => 'outwrite', "past" => 'outwrote', "participle" => 'outwritten', "description" => 'To be better at writing'],
            ["base" => 'overbear', "past" => 'overbore', "participle" => 'overborne', "description" => 'To use force or authority to control'],
            ["base" => 'overbid', "past" => 'overbid', "participle" => 'overbid', "description" => 'To bid more something is worth, To bid more than you can win in a card game'],
            ["base" => 'overblow', "past" => 'overblew', "participle" => 'overblown', "description" => 'To become subdued, To blow away To force too much'],
            ["base" => 'overbreed', "past" => 'overbred', "participle" => 'overbred', "description" => 'To breed too much so that features become excessive'],
            ["base" => 'overbuild', "past" => 'overbuilt', "participle" => 'overbuilt', "description" => 'To build too much, overdevelop'],
            ["base" => 'overbuy', "past" => 'overbought', "participle" => 'overbought', "description" => 'To buy too much, To pay too much'],
            ["base" => 'overcast', "past" => 'overcast', "participle" => 'overcast', "description" => 'To become cloudy, To sew with overcast stitches (long slanting stitches)'],
            ["base" => 'overcome', "past" => 'overcame', "participle" => 'overcome', "description" => 'To master a problem or difficult situation, To bec…se of excessive emotions or physical difficulties'],
            ["base" => 'overcut', "past" => 'overcut', "participle" => 'overcut', "description" => 'To cut down more trees than permitted'],
            ["base" => 'overdo', "past" => 'overdid', "participle" => 'overdone', "description" => 'To do something to excess, To cook something too much'],
            ["base" => 'overdraw', "past" => 'overdrew', "participle" => 'overdrawn', "description" => 'To take money out of an account so that a negative balance results'],
            ["base" => 'overdrink', "past" => 'overdrank', "participle" => 'overdrunk', "description" => 'To drink too much'],
            ["base" => 'overdrive', "past" => 'overdrove', "participle" => 'overdriven', "description" => 'To drive or work something too hard'],
            ["base" => 'overeat', "past" => 'overate', "participle" => 'overeaten', "description" => 'To eat too much'],
            ["base" => 'overfeed', "past" => 'overfed', "participle" => 'overfed', "description" => 'To give too much food'],
            ["base" => 'overfly', "past" => 'overflew', "participle" => 'overflown', "description" => 'To fly over a place'],
            ["base" => 'overgrow', "past" => 'overgrew', "participle" => 'overgrown', "description" => 'To grow too big or beyond a limit or boundary'],
            ["base" => 'overhang', "past" => 'overhung', "participle" => 'overhung', "description" => 'To be above something'],
            ["base" => 'overhear', "past" => 'overheard', "participle" => 'overheard', "description" => 'To hear something accidentally that was not said to you'],
            ["base" => 'overlay', "past" => 'overlaid', "participle" => 'overlaid', "description" => 'To cover something with a layer'],
            ["base" => 'overleap', "past" => 'overleapt or overleaped', "participle" => 'overleapt or overleaped', "description" => 'To jump over'],
            ["base" => 'overlearn', "past" => 'overlearnt or overlearned', "participle" => 'overlearnt or overlearned', "description" => 'To continue learning after having reached a basic proficiency'],
            ["base" => 'overset', "past" => 'overset', "participle" => 'overset', "description" => 'To overpower'],
            ["base" => 'oversew', "past" => 'oversewed', "participle" => 'oversewn or oversewed', "description" => 'To sew two edges together with stitches overlapping both'],
            ["base" => 'overshoot', "past" => 'overshot', "participle" => 'overshot', "description" => 'To go "past" a limit'],
            ["base" => 'oversleep', "past" => 'overslept', "participle" => 'overslept', "description" => 'To sleep too late'],
            ["base" => 'oversow', "past" => 'oversowed', "participle" => 'oversowed', "description" => 'To sow on land that has already be sown'],
            ["base" => 'overspeak', "past" => 'overspoke', "participle" => 'overspoken', "description" => 'To speak too long or use too many words'],
            ["base" => 'overspend', "past" => 'overspent', "participle" => 'overspent', "description" => 'To spend more than allowed or budgeted'],
            ["base" => 'overspill', "past" => 'overspilt or overspilled', "participle" => 'overspilt or overspilled', "description" => 'To spill over, To have a population that exceeds the space available'],
            ["base" => 'overspin', "past" => 'overspun', "participle" => 'overspun', "description" => 'To make something last too long'],
            ["base" => 'overspread', "past" => 'overspread', "participle" => 'overspread', "description" => 'To cover something'],
            ["base" => 'overspring', "past" => 'oversprang', "participle" => 'oversprung', "description" => 'To jump over'],
            ["base" => 'overstand', "past" => 'overstood', "participle" => 'overstood', "description" => 'Lose a sale of deal by sticking to a price or conditions unacceptable to the other party'],
            ["base" => 'overstrew', "past" => 'overstrewed', "participle" => 'overstrewed or overstrewn', "description" => 'To sprinkle or strew something onto another thing'],
            ["base" => 'overstride', "past" => 'overstrode', "participle" => 'overstridden', "description" => 'To walk across or over, To walk faster than someone To dominate'],
            ["base" => 'overstrike', "past" => 'overstruck', "participle" => 'overstruck', "description" => 'To stamp a new value or inscription on a old coin'],
            ["base" => 'overstring', "past" => 'overstrung', "participle" => 'overstrung', "description" => 'To tie a string too tightly, To string piano bass strings across treble strings'],
            ["base" => 'overtake', "past" => 'overtook', "participle" => 'overtaken', "description" => 'To pass a vehicle that is going more slowly'],
            ["base" => 'overthink', "past" => 'overthought', "participle" => 'overthought', "description" => 'To think or plan too much'],
            ["base" => 'overthrow', "past" => 'overthrew', "participle" => 'overthrown', "description" => 'To remove someone forcibly from government or power'],
            ["base" => 'overwear', "past" => 'overwore', "participle" => 'overworn', "description" => 'To wear something too much or often, or wear it out'],
            ["base" => 'overwind', "past" => 'overwound', "participle" => 'overwound', "description" => 'To wind a clock or something too much so it strains the spring'],
            ["base" => 'overwithhold', "past" => 'overwithheld', "participle" => 'overwithheld', "description" => 'To deduct too much tax from a payment or salary'],
            ["base" => 'overwrite', "past" => 'overwrote', "participle" => 'overwritten', "description" => 'To record data on top of existing data, erasing the original'],
            ["base" => 'partake', "past" => 'partook', "participle" => 'partaken', "description" => 'To take part in something or a part of something, usually food'],
            ["base" => 'pay', "past" => 'paid', "participle" => 'paid', "description" => 'To give somebody money in exchange for things or services'],
            ["base" => 'pen', "past" => 'pent or penned', "participle" => 'pent or penned', "description" => 'To shut up or enclose in a cage, etc'],
            ["base" => 'pinch-hit', "past" => 'pinch-hit', "participle" => 'pinch-hit', "description" => 'To bat instead of a player in "base"ball, especially when a hit is needed'],
            ["base" => 'plead', "past" => 'pled or pleaded', "participle" => 'pled or pleaded', "description" => 'To tell a court that you are guilty or innocent, To ask for special treatment by authorities, etc.'],
            ["base" => 'potshot', "past" => 'potshot or potshotted', "participle" => 'potshot', "description" => 'To shoot at random To criticise at random'],
            ["base" => 'practice-teach', "past" => 'practice-taught', "participle" => 'practice-taught', "description" => 'To teach as part of training'],
            ["base" => 'prebind', "past" => 'prebound', "participle" => 'prebound', "description" => 'To bind before'],
            ["base" => 'prebuild', "past" => 'prebuilt', "participle" => 'prebuilt', "description" => 'Prefabricate'],
            ["base" => 'precut', "past" => 'precut', "participle" => 'precut', "description" => 'To cut something before selling or assembling it'],
            ["base" => 'predo', "past" => 'predid', "participle" => 'predone', "description" => 'To do something before a certain time of stage'],
            ["base" => 'premake', "past" => 'premade', "participle" => 'premade', "description" => 'To make something before a time or stage'],
            ["base" => 'prepay', "past" => 'prepaid', "participle" => 'prepaid', "description" => 'To pay for something using it'],
            ["base" => 'presell', "past" => 'presold', "participle" => 'presold', "description" => 'To sell before a certain time'],
            ["base" => 'preset', "past" => 'preset', "participle" => 'preset', "description" => 'To arrange something before it is needed'],
            ["base" => 'preshrink', "past" => 'preshrank', "participle" => 'preshrunk', "description" => 'To shrink a fabric before selling it so that it will not become smaller when washed'],
            ["base" => 'presplit', "past" => 'presplit', "participle" => 'presplit', "description" => 'To split or divide before a certain time'],
            ["base" => 'price-cut', "past" => 'price-cut', "participle" => 'price-cut', "description" => 'To cut or reduce prices'],
            ["base" => 'proofread', "past" => 'proofread', "participle" => 'proofread', "description" => 'To read something checking carefully for mistakes'],
            ["base" => 'prove', "past" => 'proved', "participle" => 'proven or proved', "description" => 'To demonstrate that something is true'],
            ["base" => 'put', "past" => 'put', "participle" => 'put', "description" => 'To place something in a specific position'],
            ["base" => 'quick-freeze', "past" => 'quick-froze', "participle" => 'quick-frozen', "description" => 'To freeze something rapidly'],
            ["base" => 'quit', "past" => 'quit', "participle" => 'quit', "description" => 'To stop doing something, To resign from a job'],
            ["base" => 'rap', "past" => 'rapped or rapt', "participle" => 'rapped or rapt', "description" => 'To be very affected by strong emotion'],
            ["base" => 're-prove', "past" => 're-proved', "participle" => 're-proved', "description" => 'To prove again'],
            ["base" => 'read', "past" => 'read', "participle" => 'read', "description" => 'To look at written words and understand them'],
            ["base" => 'reave', "past" => 'reft or reaved', "participle" => 'reft or reaved', "description" => 'To deprive, To take by force'],
            ["base" => 'reawake', "past" => 'reawoke', "participle" => 'reawoken or reawaken', "description" => 'To wake up again'],
            ["base" => 'rebid', "past" => 'rebid', "participle" => 'rebid', "description" => 'To bid again'],
            ["base" => 'rebind', "past" => 'rebound', "participle" => 'rebound', "description" => 'To cover a book again'],
            ["base" => 'rebroadcast', "past" => 'rebroadcast', "participle" => 'rebroadcast', "description" => 'To transmit something on television or the radio again'],
            ["base" => 'rebuild', "past" => 'rebuilt', "participle" => 'rebuilt', "description" => 'To build something again'],
            ["base" => 'recast', "past" => 'recast', "participle" => 'recast', "description" => 'To replace an actor or actress'],
            ["base" => 'recut', "past" => 'recut', "participle" => 'recut', "description" => 'To cut again or differently'],
            ["base" => 'redd', "past" => 'redd or redded', "participle" => 'redd or redded', "description" => 'To save or rescue'],
            ["base" => 'redeal', "past" => 'redealt', "participle" => 'redealt', "description" => 'To deal playing cards again'],
            ["base" => 'redo', "past" => 'redid', "participle" => 'redone', "description" => 'To do something again'],
            ["base" => 'redraw', "past" => 'redrew', "participle" => 'redrawn', "description" => 'To draw again'],
            ["base" => 'reeve', "past" => 'rove or reeved', "participle" => 'rove or reeved', "description" => 'To gather together, To thread something through a hole'],
            ["base" => 'refit', "past" => 'refit', "participle" => 'refit', "description" => 'To repair a ship, plane or vehicle, To fit something again'],
            ["base" => 'regrind', "past" => 'reground', "participle" => 'reground', "description" => 'To grind again, To smooth worn engine parts'],
            ["base" => 'regrow', "past" => 'regrew', "participle" => 'regrown', "description" => 'To grow again'],
            ["base" => 'rehang', "past" => 'rehung', "participle" => 'rehung', "description" => 'To hang again or in a different position'],
            ["base" => 'rehear', "past" => 'reheard', "participle" => 'reheard', "description" => 'To hear something again'],
            ["base" => 'reknit', "past" => 'reknit or reknitted', "participle" => 'reknit or reknitted', "description" => 'To knit again, To join back together'],
            ["base" => 'relay', "past" => 'relaid', "participle" => 'relaid', "description" => 'To operate a system where things are replaced as they become used or tired'],
            ["base" => 'relearn', "past" => 'relearnt or relearned', "participle" => 'relearnt or relearned', "description" => 'To learn again'],
            ["base" => 'relight', "past" => 'relit or relighted', "participle" => 'relit or relighted', "description" => 'To light or start something burning again'],
            ["base" => 'remake', "past" => 'remade', "participle" => 'remade', "description" => 'To make something again, such as a new version of a film'],
            ["base" => 'rend', "past" => 'rent', "participle" => 'rent', "description" => 'To tear or rip'],
            ["base" => 'repay', "past" => 'repaid', "participle" => 'repaid', "description" => 'To pay somebody money owed'],
            ["base" => 'reread', "past" => 'reread', "participle" => 'reread', "description" => 'To read again'],
            ["base" => 'rerun', "past" => 'reran', "participle" => 'rerun', "description" => 'To show a film again'],
            ["base" => 'resell', "past" => 'resold', "participle" => 'resold', "description" => 'To sell something again'],
            ["base" => 'resend', "past" => 'resent', "participle" => 'resent', "description" => 'To send something again'],
            ["base" => 'reset', "past" => 'reset', "participle" => 'reset', "description" => 'To put something back to the original way it was organised'],
            ["base" => 'resew', "past" => 'resewed', "participle" => 'resewn', "description" => 'To sew again'],
            ["base" => 'reshoot', "past" => 'reshot', "participle" => 'reshot', "description" => 'To shoot a film scene again'],
            ["base" => 'resit', "past" => 'resat', "participle" => 'resat', "description" => 'To take an exam or test again'],
            ["base" => 'resow', "past" => 'resowed', "participle" => 'resown or resowed', "description" => 'To sow again'],
            ["base" => 'respell', "past" => 'respelled or respelt', "participle" => 'respelled or respelt', "description" => 'To spell again'],
            ["base" => 'restring', "past" => 'restrung', "participle" => 'restrung', "description" => 'To fit new strings on a musical instrument or a bow'],
            ["base" => 'retake', "past" => 'retook', "participle" => 'retaken', "description" => 'Take again, especially exams and tests'],
            ["base" => 'reteach', "past" => 'retaught', "participle" => 'retaught', "description" => 'To teach again'],
            ["base" => 'retear', "past" => 'retore', "participle" => 'retorn', "description" => 'To tear again, usually of injuries'],
            ["base" => 'retell', "past" => 'retold', "participle" => 'retold', "description" => 'To tell something again'],
            ["base" => 'rethink', "past" => 'rethought', "participle" => 'rethought', "description" => 'To think again'],
            ["base" => 'retread', "past" => 'retrod', "participle" => 'retrodden', "description" => 'To tread again, To cut new tread in a tyre'],
            ["base" => 'retrofit', "past" => 'retrofit or retrofitted', "participle" => 'retrofit or retrofitted', "description" => "To fit new parts into an older machine that weren't available when the machine was made"],
            ["base" => 'rewake', "past" => 'rewoke or rewaked', "participle" => 'rewoken or rewaked', "description" => 'To wake again'],
            ["base" => 'reweave', "past" => 'rewove or reweaved', "participle" => 'rewoven or reweaved', "description" => 'To weave again'],
            ["base" => 'rewed', "past" => 'rewed or rewedded', "participle" => 'rewed or rewedded', "description" => 'To marry again'],
            ["base" => 'rewet', "past" => 'rewet or rewetted', "participle" => 'rewet or rewetted', "description" => 'To wet again'],
            ["base" => 'rewin', "past" => 'rewon', "participle" => 'rewon', "description" => 'To win again'],
            ["base" => 'rewind', "past" => 'rewound', "participle" => 'rewound', "description" => 'To put a cassette or video back to the beginning'],
            ["base" => 'rewrite', "past" => 'rewrote', "participle" => 'rewritten', "description" => 'To write something again, usually with improvements'],
            ["base" => 'rid', "past" => 'rid or ridded', "participle" => 'rid or ridded', "description" => 'To dispose of'],
            ["base" => 'ride', "past" => 'rode', "participle" => 'ridden', "description" => 'To travel by horse, bike or motorbike'],
            ["base" => 'ring', "past" => 'rang', "participle" => 'rung', "description" => 'To telephone, To make sounds with a bell'],
            ["base" => 'rise', "past" => 'rose', "participle" => 'risen', "description" => 'To move upwards'],
            ["base" => 'rive', "past" => 'rived', "participle" => 'riven or rived', "description" => 'To break apart ot split'],
            ["base" => 'rough-hew', "past" => 'rough-hewed', "participle" => 'rough-hewn', "description" => 'To make a rough version of something'],
            ["base" => 'roughcast', "past" => 'roughcast', "participle" => 'roughcast', "description" => 'To prepare a rough form of something'],
            ["base" => 'run', "past" => 'ran', "participle" => 'run', "description" => 'To move quickly, so that both legs leave the ground'],
            ["base" => 'sand-cast', "past" => 'sand-cast', "participle" => 'sand-cast', "description" => 'To make a cast by pouring metal into a mold made of sand.'],
            ["base" => 'saw', "past" => 'sawed', "participle" => 'sawn or sawed', "description" => 'To cut wood, etc, with a tool'],
            ["base" => 'say', "past" => 'said', "participle" => 'said', "description" => 'To speak words'],
            ["base" => 'see', "past" => 'saw', "participle" => 'seen', "description" => 'To notice with your eyes'],
            ["base" => 'seek', "past" => 'sought', "participle" => 'sought', "description" => 'To try to find something'],
            ["base" => 'self-feed', "past" => 'self-fed', "participle" => 'self-fed', "description" => 'To feed itself without assistance'],
            ["base" => 'self-sow', "past" => 'self-sowed', "participle" => 'self-sown or self-sowed', "description" => 'To sow itself without assistance'],
            ["base" => 'sell', "past" => 'sold', "participle" => 'sold', "description" => 'To receive money in exchange for goods'],
            ["base" => 'send', "past" => 'sent', "participle" => 'sent', "description" => 'To cause something to be taken to a specific destination, especially letters, message, etc.'],
            ["base" => 'set', "past" => 'set', "participle" => 'set', "description" => 'To place something somewhere, To fix something in a particular position'],
            ["base" => 'sew', "past" => 'sewed', "participle" => 'sewn or sewed', "description" => 'To join pieces of material together using thread'],
            ["base" => 'shake', "past" => 'shook', "participle" => 'shaken', "description" => 'To vibrate To make something vibrate'],
            ["base" => 'shave', "past" => 'shaved', "participle" => 'shaven or shaved', "description" => 'To remove body hair'],
            ["base" => 'shear', "past" => 'shore or sheared', "participle" => 'shorn or sheared', "description" => 'To cut with scissors, especially wool from sheep'],
            ["base" => 'shed', "past" => 'shed', "participle" => 'shed', "description" => 'To fall off or let something fall off; snakes shed their skin'],
            ["base" => 'shend', "past" => 'shent', "participle" => 'shent', "description" => 'To shame or disgrace'],
            ["base" => 'shew', "past" => 'shewed', "participle" => 'shewn or shewed', "description" => 'Show'],
            ["base" => 'shine', "past" => 'shone', "participle" => 'shone', "description" => 'To give off or reflect bright light'],
            ["base" => 'shit', "past" => 'shat or shit', "participle" => 'shat or shit', "description" => 'To get rid of solid body waste'],
            ["base" => 'shoe', "past" => 'shod', "participle" => 'shod', "description" => 'To provide with shoes, especially horses'],
            ["base" => 'shoot', "past" => 'shot', "participle" => 'shot', "description" => 'To fire a bullet from a gun, To kill or hurt somebody with a gun'],
            ["base" => 'shortcut', "past" => 'shortcut', "participle" => 'shortcut', "description" => 'To use a shorter or quicker way of going somewhere or doing something'],
            ["base" => 'show', "past" => 'showed', "participle" => 'shown', "description" => 'To allow somebody to see something so that they can become aware of it'],
            ["base" => 'shrink', "past" => 'shrank', "participle" => 'shrunk', "description" => 'To become smaller, To make something smaller'],
            ["base" => 'shrive', "past" => 'shrove', "participle" => 'shriven', "description" => 'To confess or listen to a confession, a religious term'],
            ["base" => 'shut', "past" => 'shut', "participle" => 'shut', "description" => 'To close something'],
            ["base" => 'sidewind', "past" => 'sidewound', "participle" => 'sidewound', "description" => 'To move like the sidewinder snake'],
            ["base" => 'sight-read', "past" => 'sight-read', "participle" => 'sight-read', "description" => 'To read music'],
            ["base" => 'sightsee', "past" => 'sightsaw', "participle" => 'sightseen', "description" => 'To visit famous monuments, etc'],
            ["base" => 'sing', "past" => 'sang', "participle" => 'sung', "description" => 'To make music with your voice'],
            ["base" => 'sink', "past" => 'sank', "participle" => 'sunk', "description" => 'To move downwards in water, To make something move downwards in water'],
            ["base" => 'sit', "past" => 'sat', "participle" => 'sat', "description" => 'To support your body with your buttocks not your f…ith the back in a vertical position as on a chair'],
            ["base" => 'skywrite', "past" => 'skywrote', "participle" => 'skywritten', "description" => 'To write in the sky with smoke'],
            ["base" => 'slay', "past" => 'slew', "participle" => 'slain', "description" => 'To kill'],
            ["base" => 'sleep', "past" => 'slept', "participle" => 'slept', "description" => 'To be in a relaxed state with your eyes closed'],
            ["base" => 'slide', "past" => 'slid', "participle" => 'slid or slidden', "description" => 'To move on a smooth surface, such as ice'],
            ["base" => 'sling', "past" => 'slung', "participle" => 'slung', "description" => 'To throw something somewhere'],
            ["base" => 'slink', "past" => 'slunk', "participle" => 'slunk', "description" => 'To move in a suspicious and guilty way'],
            ["base" => 'slit', "past" => 'slit', "participle" => 'slit', "description" => 'To make a long thin cut in something'],
            ["base" => 'smell', "past" => 'smelt or smelled', "participle" => 'smelt or smelled', "description" => 'To detect odours with your nose, To emit odours'],
            ["base" => 'smite', "past" => 'smote', "participle" => 'smitten', "description" => 'To hit'],
            ["base" => 'snapshoot', "past" => 'snapshot', "participle" => 'snapshot', "description" => 'Take a quick photograph'],
            ["base" => 'sneak', "past" => 'sneaked or snuck', "participle" => 'sneaked or snuck', "description" => 'To move around guiltily or to avoid being noticed'],
            ["base" => 'soothsay', "past" => 'soothsaid', "participle" => 'soothsaid', "description" => 'To predict the future'],
            ["base" => 'sow', "past" => 'sowed', "participle" => 'sown', "description" => 'To plant seeds in the ground to produce plants or cereals'],
            ["base" => 'speak', "past" => 'spoke', "participle" => 'spoken', "description" => 'To say words with your mouth, To be able to use a language'],
            ["base" => 'speed', "past" => 'sped or speeded', "participle" => 'sped or speeded', "description" => 'To move quickly, To drive faster than legally permitted'],
            ["base" => 'spell', "past" => 'spelt or spelled', "participle" => 'spelt or spelled', "description" => 'To use the correct combination of letters for a word'],
            ["base" => 'spellbind', "past" => 'spellbound', "participle" => 'spellbound', "description" => 'To put into a trance or captivate'],
            ["base" => 'spend', "past" => 'spent', "participle" => 'spent', "description" => 'To use money to buy things, To use time or energy doing something'],
            ["base" => 'spill', "past" => 'spilt or spilled', "participle" => 'spilt or spilled', "description" => 'To allow liquids out of their containers accidentally'],
            ["base" => 'spin', "past" => 'span or spun', "participle" => 'spun', "description" => 'To turn repeatedly in circles around a fixed point, To make something turn repeatedly in circles'],
            ["base" => 'spit', "past" => 'spat or spit', "participle" => 'spat or spit', "description" => 'To eject saliva, liquid or food from the mouth'],
            ["base" => 'split', "past" => 'split', "participle" => 'split', "description" => 'To divide, To break open'],
            ["base" => 'spoil', "past" => 'spoilt or spoiled', "participle" => 'spoilt or spoiled', "description" => 'To let something go bad, To go bad'],
            ["base" => 'spoonfeed', "past" => 'spoonfed', "participle" => 'spoonfed', "description" => 'To give someone information in small and very easy bits'],
            ["base" => 'spread', "past" => 'spread', "participle" => 'spread', "description" => 'To cover the surface of one thing with'],
            ["base" => 'spring', "past" => 'sprang', "participle" => 'sprung', "description" => 'To jump To become active'],
            ["base" => 'stall-feed', "past" => 'stall-fed', "participle" => 'stall-fed', "description" => 'To feed or fatten an animal in a stall'],
            ["base" => 'stand', "past" => 'stood', "participle" => 'stood', "description" => 'To be in a vertical position with the weight on the feet, To get into this position'],
            ["base" => 'stave', "past" => 'stove or staved or stoved', "participle" => 'stove or staved or stoved', "description" => 'To break a hole in something'],
            ["base" => 'steal', "past" => 'stole', "participle" => 'stolen', "description" => 'To take property or money that is not yours'],
            ["base" => 'stick', "past" => 'stuck', "participle" => 'stuck', "description" => 'To attach things with glue, To insert a sharp object into something'],
            ["base" => 'sting', "past" => 'stung', "participle" => 'stung', "description" => 'To feel pain caused by an insect or plant or in a particular part of the body'],
            ["base" => 'stink', "past" => 'stank', "participle" => 'stunk', "description" => 'To smell very badly'],
            ["base" => 'straphang', "past" => 'straphung', "participle" => 'straphung', "description" => 'To hold a strap for support'],
            ["base" => 'strew', "past" => 'strewed', "participle" => 'strewn or strewed', "description" => 'To distribute things randomly over a surface'],
            ["base" => 'stride', "past" => 'strode or strided', "participle" => 'stridden', "description" => 'To walk confidently'],
            ["base" => 'strike', "past" => 'struck', "participle" => 'struck or stricken', "description" => 'To stop working as a protest about working conditions, To hit'],
            ["base" => 'string', "past" => 'strung', "participle" => 'strung', "description" => 'To attach something using a cord'],
            ["base" => 'strip', "past" => 'stript or stripped', "participle" => 'stript or stripped', "description" => 'To undress, To remove the covering of something'],
            ["base" => 'strive', "past" => 'strove', "participle" => 'striven', "description" => 'To try very hard to do something'],
            ["base" => 'sublet', "past" => 'sublet', "participle" => 'sublet', "description" => 'To rent something you have rented'],
            ["base" => 'sunburn', "past" => 'sunburned or sunburnt', "participle" => 'sunburned or sunburnt', "description" => 'To get red skin from being in the sun for too long'],
            ["base" => 'swear', "past" => 'swore', "participle" => 'sworn', "description" => 'To use words which are regarded as offensive, To promise'],
            ["base" => 'sweat', "past" => 'sweat or sweated', "participle" => 'sweat or sweated', "description" => 'To perspire'],
            ["base" => 'sweep', "past" => 'swept or sweeped', "participle" => 'swept or sweeped', "description" => 'To clean floors using a brush'],
            ["base" => 'swell', "past" => 'swelled', "participle" => 'swollen', "description" => 'To increase in size usually by filling with liquids or gases'],
            ["base" => 'swim', "past" => 'swam', "participle" => 'swum', "description" => 'To travel in water by moving your arms and legs'],
            ["base" => 'swing', "past" => 'swung', "participle" => 'swung', "description" => 'To move from side to side from a fixed point'],
            ["base" => 'swink', "past" => 'swank or swonk', "participle" => 'swonken', "description" => 'To work, toil or labour'],
            ["base" => 'switch-hit', "past" => 'switch-hit', "participle" => 'switch-hit', "description" => 'To bat right-handed against a left-handed bowler, or vice versa, in "base"ball'],
            ["base" => 'take', "past" => 'took', "participle" => 'taken', "description" => 'To perform an action, To acquire'],
            ["base" => 'teach', "past" => 'taught', "participle" => 'taught', "description" => 'To instruct or train somebody'],
            ["base" => 'tear', "past" => 'tore', "participle" => 'torn', "description" => 'To make a hole or divide material, paper, etc.'],
            ["base" => 'telecast', "past" => 'telecast or telecasted', "participle" => 'telecast or telecasted', "description" => 'To broadcast on TV'],
            ["base" => 'tell', "past" => 'told', "participle" => 'told', "description" => 'To give somebody information'],
            ["base" => 'test-drive', "past" => 'test-drove', "participle" => 'test-driven', "description" => 'To drive a car to test it before buying'],
            ["base" => 'test-fly', "past" => 'test-flew', "participle" => 'test-flown', "description" => 'To test a plane'],
            ["base" => 'think', "past" => 'thought', "participle" => 'thought', "description" => 'To have an opinion To use the brain'],
            ["base" => 'thrive', "past" => 'throve or thrived', "participle" => 'thriven or thrived', "description" => 'To do very well because the circumstances or situation is right'],
            ["base" => 'throw', "past" => 'threw', "participle" => 'thrown', "description" => 'To cause an object to leave your hand in such a way that it travels through the air'],
            ["base" => 'thrust', "past" => 'thrust', "participle" => 'thrust', "description" => 'To push with force'],
            ["base" => 'thunderstrike', "past" => 'thunderstruck', "participle" => 'thunderstruck or thunderstricken', "description" => 'To strike with lightning, To shock'],
            ["base" => 'tine', "past" => 'tint or tined', "participle" => 'tint or tined', "description" => 'To shut'],
            ["base" => 'tread', "past" => 'trod', "participle" => 'trodden', "description" => 'To put your foot down'],
            ["base" => 'troubleshoot', "past" => 'troubleshot', "participle" => 'troubleshot', "description" => 'To solve a problem'],
            ["base" => 'typecast', "past" => 'typecast', "participle" => 'typecast', "description" => 'To give an actor the same sort of role repeatedly'],
            ["base" => 'typeset', "past" => 'typeset', "participle" => 'typeset', "description" => 'To compose type for printing'],
            ["base" => 'typewrite', "past" => 'typewrote', "participle" => 'typewritten', "description" => 'To write with a typewriter'],
            ["base" => 'unbear', "past" => 'unbore', "participle" => 'unborn or unborne', "description" => "To remove a horse's rein and straps"],
            ["base" => 'unbend', "past" => 'unbent', "participle" => 'unbent', "description" => 'To retore something to its original shape that has been distorted'],
            ["base" => 'unbind', "past" => 'unbound', "participle" => 'unbound', "description" => 'To set something free, To untie, remove ropes, chains, etc..'],
            ["base" => 'unbuild', "past" => 'unbuilt', "participle" => 'unbuilt', "description" => 'To demolish'],
            ["base" => 'unclothe', "past" => 'unclad or unclothed', "participle" => 'unclad or unclothed', "description" => 'To remove clothes'],
            ["base" => 'underbid', "past" => 'underbid', "participle" => 'underbid', "description" => 'To offer less money in an auction or sale'],
            ["base" => 'underbuy', "past" => 'underbought', "participle" => 'underbought', "description" => 'To buy for less than the real value'],
            ["base" => 'undercut', "past" => 'undercut', "participle" => 'undercut', "description" => 'To sell at a cheaper price than a competitor'],
            ["base" => 'underdo', "past" => 'underdid', "participle" => 'underdone', "description" => 'To do less than necessary, Not to cook enough'],
            ["base" => 'underfeed', "past" => 'underfed', "participle" => 'underfed', "description" => 'To give too little food to someone or an animal'],
            ["base" => 'undergird', "past" => 'undergirt or undergirded', "participle" => 'undergirt or undergirded', "description" => 'To make something secure underneath, To give moral support'],
            ["base" => 'undergo', "past" => 'underwent', "participle" => 'undergone', "description" => 'To suffer or go through an unpleasant experience, such as surgery'],
            ["base" => 'underlay', "past" => 'underlaid', "participle" => 'underlaid', "description" => 'To put underneath something'],
            ["base" => 'underlet', "past" => 'underlet', "participle" => 'underlet', "description" => 'To rent for less than the real value'],
            ["base" => 'underlie', "past" => 'underlay', "participle" => 'underlain', "description" => 'To be the real reason, meaning or idea behind something, usually hidden or not clear'],
            ["base" => 'underpay', "past" => 'underpaid', "participle" => 'underpaid', "description" => 'To pay someone too little or pay less than the price'],
            ["base" => 'underrun', "past" => 'underran', "participle" => 'underrun', "description" => 'To pass or flow underneath something'],
            ["base" => 'undersell', "past" => 'undersold', "participle" => 'undersold', "description" => 'To sell at a lower price than a competitor'],
            ["base" => 'undershoot', "past" => 'undershot', "participle" => 'undershot', "description" => 'To shoot too short, Not to reach a target'],
            ["base" => 'underspend', "past" => 'underspent', "participle" => 'underspent', "description" => "To spend less money than allocated in the department or company's budget"],
            ["base" => 'understand', "past" => 'understood', "participle" => 'understood', "description" => 'To know or come to know the meaning of something'],
            ["base" => 'undertake', "past" => 'undertook', "participle" => 'undertaken', "description" => 'To accept responsibility for doing something'],
            ["base" => 'underthrust', "past" => 'underthrust', "participle" => 'underthrust', "description" => 'To insert faulted rock under a passive rock mass'],
            ["base" => 'underwrite', "past" => 'underwrote', "participle" => 'underwritten', "description" => 'To accept part or all of a financial risk, especially insurance'],
            ["base" => 'undo', "past" => 'undid', "participle" => 'undone', "description" => "To ruin somebody's reputation, To 'open' clothes or shoes before taking them off"],
            ["base" => 'undraw', "past" => 'undrew', "participle" => 'undrawn', "description" => 'To open, draw back (curtains, etc)'],
            ["base" => 'unfreeze', "past" => 'unfroze', "participle" => 'unfrozen', "description" => 'To make assets available for use, To thaw something'],
            ["base" => 'unhang', "past" => 'unhung', "participle" => 'unhung', "description" => 'To remove something that is hanging'],
            ["base" => 'unhide', "past" => 'unhid', "participle" => 'unhidden', "description" => 'To expose something that was hidden'],
            ["base" => 'unhold', "past" => 'unheld', "participle" => 'unheld', "description" => 'To stop holding or not to hold'],
            ["base" => 'unknit', "past" => 'unknit or unknitted', "participle" => 'unknit or unknitted', "description" => 'To untie'],
            ["base" => 'unlade', "past" => 'unladed', "participle" => 'unladen or unladed', "description" => 'To remove cargo, unload'],
            ["base" => 'unlay', "past" => 'unlaid', "participle" => 'unlaid', "description" => 'To untwist a rope'],
            ["base" => 'unlearn', "past" => 'unlearnt or unlearned', "participle" => 'unlearnt or unlearned', "description" => 'To try to forget or change a habit or something that had been learned'],
            ["base" => 'unmake', "past" => 'unmade', "participle" => 'unmade', "description" => 'To remove a decision'],
            ["base" => 'unreeve', "past" => 'unrove or unreeved', "participle" => 'unrove or unreeved', "description" => 'To remove a rope from a hook'],
            ["base" => 'unsay', "past" => 'unsaid', "participle" => 'unsaid', "description" => 'Not to say something, To take back something that you said'],
            ["base" => 'unsell', "past" => 'unsold', "participle" => 'unsold', "description" => 'To convince someone that something is worthless or false'],
            ["base" => 'unsew', "past" => 'unsewed', "participle" => 'unsewn or unsewed', "description" => 'To undo someone sewed, remove the stitches'],
            ["base" => 'unsling', "past" => 'unslung', "participle" => 'unslung', "description" => 'To remove something held in a sling'],
            ["base" => 'unspeak', "past" => 'unspoke', "participle" => 'unspoken', "description" => 'To take back what has been said or not to say something'],
            ["base" => 'unspin', "past" => 'unspun', "participle" => 'unspun', "description" => 'To untwist or unravel'],
            ["base" => 'unstick', "past" => 'unstuck', "participle" => 'unstuck', "description" => 'To separate things that have been stuck together, To take off'],
            ["base" => 'unstring', "past" => 'unstrung', "participle" => 'unstrung', "description" => 'To open something secured with string'],
            ["base" => 'unswear', "past" => 'unswore', "participle" => 'unsworn', "description" => 'To take back an oath'],
            ["base" => 'unteach', "past" => 'untaught', "participle" => 'untaught', "description" => 'To make someone forget something they have learned'],
            ["base" => 'unthink', "past" => 'unthought', "participle" => 'unthought', "description" => 'To remove something from your mind'],
            ["base" => 'untread', "past" => 'untrod', "participle" => 'untrodden', "description" => 'To tread back, retrace your steps'],
            ["base" => 'unweave', "past" => 'unwove', "participle" => 'unwoven', "description" => 'To undo things that have been woven together'],
            ["base" => 'unwind', "past" => 'unwound', "participle" => 'unwound', "description" => 'To relax'],
            ["base" => 'unwrite', "past" => 'unwrote', "participle" => 'unwritten', "description" => 'To delete writing or not to write'],
            ["base" => 'upbuild', "past" => 'upbuilt', "participle" => 'upbuilt', "description" => 'To build up, develop on a large scale'],
            ["base" => 'uphold', "past" => 'upheld', "participle" => 'upheld', "description" => 'To support or confirm a decision'],
            ["base" => 'uppercut', "past" => 'uppercut', "participle" => 'uppercut', "description" => "To punch upwards towards someone's chin"],
            ["base" => 'uprise', "past" => 'uprose', "participle" => 'uprisen', "description" => 'To get up, stand up, move up, To return from the dead'],
            ["base" => 'upset', "past" => 'upset', "participle" => 'upset', "description" => 'To make somebody unhappy or disturbed'],
            ["base" => 'upspring', "past" => 'upsprang', "participle" => 'upsprung', "description" => 'To jump or spring up'],
            ["base" => 'upsweep', "past" => 'upswept', "participle" => 'upswept', "description" => 'To sweep or brush upwards'],
            ["base" => 'uptear', "past" => 'uptore', "participle" => 'uptorn', "description" => 'To tear into pieces'],
            ["base" => 'vex', "past" => 'vext or vexed', "participle" => 'vext or vexed', "description" => 'To trouble or annoy'],
            ["base" => 'wake', "past" => 'woke', "participle" => 'woken', "description" => 'To stop sleeping and become conscious, To make somebody stop sleeping'],
            ["base" => 'waylay', "past" => 'waylaid', "participle" => 'waylaid', "description" => 'To wait for or to stop somebody to rob them'],
            ["base" => 'wear', "past" => 'wore', "participle" => 'worn', "description" => 'To have clothes on your body'],
            ["base" => 'weave', "past" => 'wove', "participle" => 'woven', "description" => 'To make material'],
            ["base" => 'wed', "past" => 'wed or wedded', "participle" => 'wed or wedded', "description" => 'To marry'],
            ["base" => 'weep', "past" => 'wept', "participle" => 'wept', "description" => 'To cry heavily'],
            ["base" => 'wend', "past" => 'wended or went', "participle" => 'wended or went', "description" => 'To go, make your way'],
            ["base" => 'wet', "past" => 'wet or wetted', "participle" => 'wet or wetted', "description" => 'To make something wet by applying a liquid to it'],
            ["base" => 'whipsaw', "past" => 'whipsawed', "participle" => 'whipsawn or whipsawed', "description" => 'To cut with whipsaw (a saw for two people), To victimise'],
            ["base" => 'win', "past" => 'won', "participle" => 'won', "description" => 'To be the best in a competition, game, election, etc.'],
            ["base" => 'wind', "past" => 'wound', "participle" => 'wound', "description" => 'To turn something round to make a mechanical process operate'],
            ["base" => 'winterfeed', "past" => 'winterfed', "participle" => 'winterfed', "description" => "To feed cattle in the winter when they can't graze"],
            ["base" => 'wiredraw', "past" => 'wiredrew', "participle" => 'wiredrawn', "description" => 'To make wire, To make something last a long time, especially speech'],
            ["base" => 'wit', "past" => 'wist', "participle" => 'wist', "description" => 'To know'],
            ["base" => 'withdraw', "past" => 'withdrew', "participle" => 'withdrawn', "description" => 'To remove money from a bank, To remove something from a place'],
            ["base" => 'withhold', "past" => 'withheld', "participle" => 'withheld', "description" => 'Not to let somebody have something'],
            ["base" => 'withstand', "past" => 'withstood', "participle" => 'withstood', "description" => 'To resist successfully'],
            ["base" => 'wont', "past" => 'wont', "participle" => 'wont or wonted', "description" => 'To be accustomed'],
            ["base" => 'work', "past" => 'worked or wrought', "participle" => 'worked or wrought', "description" => 'To make physical or mental effort to produce or achieve something'],
            ["base" => 'wrap', "past" => 'wrapped or wrapt', "participle" => 'wrapped or wrapt', "description" => 'To cover, To transport emotionally'],
            ["base" => 'wreak', "past" => 'wreaked', "participle" => 'wreaked or wroken', "description" => 'To cause or make something happen'],
            ["base" => 'wring', "past" => 'wrung', "participle" => 'wrung', "description" => 'To put a lot of pressure on something to remove liquids'],
            ["base" => 'write', "past" => 'wrote', "participle" => 'written', "description" => 'To put words onto paper using a pen or pencil'],
            ["base" => 'zinc', "past" => 'zinced or zincked', "participle" => 'zinced or zincked', "description" => 'To coat or cover something with a layer of zinc']
        ];

        DB::table('irregulars')->insert($data);
    }
}